# Generated by Django 3.1.2 on 2021-12-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmn', '0003_auto_20211213_2303'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='show',
            constraint=models.UniqueConstraint(fields=('show_date', 'artist', 'venue'), name='instance_of_a_show'),
        ),
    ]
